# ensure a static (not latest) version to version stability
FROM ruby:3.2.2

WORKDIR /app

# install required gems
COPY Gemfile Gemfile.lock /app/

RUN bundle install

COPY . /app/
EXPOSE 3000
# Use the entrypoint script
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

